[tool.mypy]
strict = true
follow_imports = "skip"
ignore_missing_imports = true
namespace_packages = true
explicit_package_bases = true
disallow_subclassing_any = false
disallow_untyped_decorators = true
warn_redundant_casts = true
warn_return_any = true
warn_unreachable = true
warn_unused_configs = true


[tool.pytest.ini_options]
pythonpath = ["app", "tests"]
asyncio_mode = "auto"
asyncio_default_fixture_loop_scope = "session"

addopts = "-v"
log_cli_level = "INFO"     
log_cli_format = "%(asctime)s [%(levelname)s] %(message)s"
log_cli_date_format = "%H:%M:%S"